import type { Metadata } from 'next';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: 'Visionary AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`h-screen bg-[url("/back.webp")] bg-black/90  bg-blend-color bg-cover bg-center`}
        >
          <div className='backdrop-blur-[7px]'>{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
